version: '3.8'

services:
  postgres:
    image: pgvector/pgvector:pg15
    environment:
      POSTGRES_DB: mangoo
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/mangoo
      COGNITO_USER_POOL_ID: ${COGNITO_USER_POOL_ID}
      COGNITO_APP_CLIENT_ID: ${COGNITO_APP_CLIENT_ID}
      COGNITO_REGION: ${AWS_REGION:-us-east-1}
      BEDROCK_REGION: ${AWS_REGION:-us-east-1}
      BEDROCK_MODEL_ID: anthropic.claude-3-5-sonnet-20241022-v2:0
      BEDROCK_EMBEDDING_MODEL_ID: amazon.titan-embed-text-v2:0
      SECRET_KEY: dev-secret-key-change-in-production
      DEBUG: "true"
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_SESSION_TOKEN: ${AWS_SESSION_TOKEN}
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./backend/app:/app/app

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: build
    ports:
      - "3000:3000"
    environment:
      VITE_API_URL: http://localhost:8000
      VITE_COGNITO_USER_POOL_ID: ${COGNITO_USER_POOL_ID}
      VITE_COGNITO_CLIENT_ID: ${COGNITO_APP_CLIENT_ID}
      VITE_COGNITO_REGION: ${AWS_REGION:-us-east-1}
    volumes:
      - ./frontend/src:/app/src
    command: npm run dev

volumes:
  postgres_data:
